chromium: Ignore textrels on x86 build
Issue: LIN1021-2988

building 32bit x86 results in textrels which I guess should be fixed
so here is a workaround until they are root caused and fixed.

Fixes build time QA error

ERROR: QA Issue: lib32-chromium-ozone-wayland: ELF binary /usr/bin/chromium has relocations in .text [textrel]

(master rev: 3c81df0 )

Signed-off-by: Khem Raj <raj.khem@gmail.com>
Signed-off-by: Randy MacLeod <Randy.MacLeod@windriver.com>