firefox: use rust-common-without-python3native
Issue: LIN1021-2988

* unfortunate side-effect of:
  https://git.openembedded.org/openembedded-core/commit/meta/classes/rust-common.bbclass?id=997d54363a3cb3a0e949b3626855f2fa41afeb2b
  is that python3native is now inheritted in firefox build which causes do_configure failure:

DEBUG: Executing python function extend_recipe_sysroot
NOTE: Direct dependencies are ['virtual:native:/OE/build/test-oe-build-time/poky/meta/recipes-extended/xz/xz_5.2.5.bb:do_populate_sysroot', '/OE/build/test-oe-build-time/poky/meta/recipes-devtools/quilt/quilt-native_0.67.bb:do_populate_sysroot', 'virtual:native:/OE/build/test-oe-build-time/poky/meta/recipes-devtools/python/python3_3.10.2.bb:do_populate_sysroot', '/OE/build/test-oe-build-time/poky/meta/recipes-graphics/cairo/cairo_1.16.0.bb:do_populate_sysroot', '/OE/build/test-oe-build-time/poky/meta-clang/recipes-devtools/clang/clang-cross_git.bb:do_populate_sysroot', '/OE/build/test-oe-build-time/poky/meta/recipes-core/glibc/glibc_2.35.bb:do_populate_sysroot', 'virtual:native:/OE/build/test-oe-build-time/poky/meta/recipes-extended/unzip/unzip_6.0.bb:do_populate_sysroot', 'virtual:native:/OE/build/test-oe-build-time/poky/meta/recipes-extended/zip/zip_3.0.bb:do_populate_sysroot', 'virtual:native:/OE/build/test-oe-build-time/poky/meta-openembedded/meta-oe/recipes-devtools/yasm/yasm_git.bb:do_populate_sysroot', '/OE/build/test-oe-build-time/poky/meta-openembedded/meta-oe/recipes-gnome/gtk+/gtk+_2.24.33.bb:do_populate_sysroot', 'virtual:native:/OE/build/test-oe-build-time/poky/meta/recipes-devtools/cargo/cargo_1.59.0.bb:do_populate_sysroot', '/OE/build/test-oe-build-time/poky/meta/recipes-core/dbus/dbus-glib_0.112.bb:do_populate_sysroot', 'virtual:native:/OE/build/test-oe-build-time/poky/meta-openembedded/meta-oe/recipes-devtools/nodejs/nodejs_16.14.0.bb:do_populate_sysroot', '/OE/build/test-oe-build-time/poky/meta/recipes-devtools/rust/libstd-rs_1.59.0.bb:do_populate_sysroot', 'virtual:native:/OE/build/test-oe-build-time/poky/meta-browser/meta-firefox/recipes-devtools/cbindgen/cbindgen_0.8.7.bb:do_populate_sysroot', '/OE/build/test-oe-build-time/poky/meta/recipes-devtools/gcc/libgcc_11.2.bb:do_populate_sysroot', '/OE/build/test-oe-build-time/poky/meta/recipes-support/icu/icu_70.1.bb:do_populate_sysroot', 'virtual:native:/OE/build/test-oe-build-time/poky/meta/recipes-devtools/nasm/nasm_2.15.05.bb:do_populate_sysroot', 'virtual:native:/OE/build/test-oe-build-time/poky/meta/recipes-devtools/patch/patch_2.7.6.bb:do_populate_sysroot', '/OE/build/test-oe-build-time/poky/meta/recipes-multimedia/pulseaudio/pulseaudio_15.0.bb:do_populate_sysroot', '/OE/build/test-oe-build-time/poky/meta/recipes-multimedia/alsa/alsa-lib_1.2.6.1.bb:do_populate_sysroot', '/OE/build/test-oe-build-time/poky/meta/recipes-support/libevent/libevent_2.1.12.bb:do_populate_sysroot', '/OE/build/test-oe-build-time/poky/meta/recipes-graphics/mesa/mesa_21.3.7.bb:do_populate_sysroot', 'virtual:native:/OE/build/test-oe-build-time/poky/meta/recipes-devtools/pseudo/pseudo_git.bb:do_populate_sysroot', '/OE/build/test-oe-build-time/poky/meta/recipes-graphics/xorg-lib/libxi_1.8.bb:do_populate_sysroot', '/OE/build/test-oe-build-time/poky/meta/recipes-graphics/xorg-lib/libxt_1.2.1.bb:do_populate_sysroot', '/OE/build/test-oe-build-time/poky/meta/recipes-devtools/gcc/gcc-runtime_11.2.bb:do_populate_sysroot', '/OE/build/test-oe-build-time/poky/meta/recipes-support/curl/curl_7.82.0.bb:do_populate_sysroot', 'virtual:native:/OE/build/test-oe-build-time/poky/meta/recipes-devtools/gnu-config/gnu-config_git.bb:do_populate_sysroot', 'virtual:native:/OE/build/test-oe-build-time/poky/meta/recipes-devtools/pkgconfig/pkgconfig_git.bb:do_populate_sysroot', '/OE/build/test-oe-build-time/poky/meta/recipes-devtools/rust/rust-cross_1.59.0.bb:do_populate_sysroot', '/OE/build/test-oe-build-time/poky/meta/recipes-gnome/gtk+/gtk+3_3.24.31.bb:do_populate_sysroot', '/OE/build/test-oe-build-time/poky/meta/recipes-gnome/libnotify/libnotify_0.7.9.bb:do_populate_sysroot', '/OE/build/test-oe-build-time/poky/meta/recipes-graphics/startup-notification/startup-notification_0.12.bb:do_populate_sysroot']
NOTE: Installed into sysroot: []
NOTE: Skipping as already exists in sysroot: ['xz-native', 'quilt-native', 'python3-native', 'cairo', 'clang-cross-x86_64', 'glibc', 'unzip-native', 'zip-native', 'yasm-native', 'gtk+', 'cargo-native', 'dbus-glib', 'nodejs-native', 'libstd-rs', 'cbindgen-native', 'libgcc', 'icu', 'nasm-native', 'patch-native', 'pulseaudio', 'alsa-lib', 'libevent', 'mesa', 'pseudo-native', 'libxi', 'libxt', 'gcc-runtime', 'curl', 'gnu-config-native', 'pkgconfig-native', 'rust-cross-core2-64-glibc', 'gtk+3', 'libnotify', 'startup-notification', 'libtool-native', 'gettext-minimal-native', 'util-linux-libuuid-native', 'libnsl2-native', 'libtirpc-native', 'gdbm-native', 'sqlite3-native', 'bzip2-native', 'readline-native', 'zlib-native', 'libffi-native', 'openssl-native', 'fontconfig', 'libx11', 'glib-2.0', 'pixman', 'libpng', 'libxrender', 'libsm', 'libxcb', 'zlib', 'opkg-utils', 'libxext', 'clang-native', 'binutils-cross-x86_64', 'linux-libc-headers', 'flex-native', 'pango', 'libxcomposite', 'gobject-introspection', 'libxdamage', 'libjpeg-turbo', 'gdk-pixbuf', 'atk', 'libxcursor', 'libxrandr', 'rust-native', 'libssh2-native', 'ca-certificates-native', 'curl-native', 'bash-completion', 'expat', 'dbus', 'icu-native', 'brotli-native', 'c-ares-native', 'autoconf-archive', 'groff-native', 'attr-native', 'avahi', 'eudev', 'shadow-sysroot', 'libtool', 'bluez5', 'ofono', 'libsndfile1', 'libice', 'libcap', 'shadow', 'sbc', 'shadow-native', 'libatomic-ops', 'speexdsp', 'base-passwd', 'libxtst', 'base-files', 'libdrm', 'libxfixes', 'xrandr', 'wayland', 'xorgproto', 'libxxf86vm', 'libxshmfence', 'wayland-protocols', 'util-macros', 'libxdmcp', 'util-linux', 'libidn2', 'openssl', 'gcc-cross-x86_64', 'rust-llvm-native', 'libxkbcommon', 'libepoxy', 'at-spi2-atk', 'xcb-util', 'texinfo-dummy-native', 'ncurses-native', 'perl-native', 'freetype', 'xtrans', 'libpcre', 'libffi', 'libxau', 'libpthread-stubs', 'xcb-proto', 'libxml2-native', 'binutils-native', 'libedit-native', 'swig-native', 'cmake-native', 'm4-native', 'libxft', 'fribidi', 'harfbuzz', 'python3', 'shared-mime-info', 'initscripts', 'update-rc.d', 'libdaemon', 'kmod', 'readline', 'libical', 'mobile-broadband-provider-info', 'ell', 'flac', 'libvorbis', 'libogg', 'attr', 'libxcrypt', 'libpciaccess', 'libxml2', 'libcap-ng', 'ncurses', 'util-linux-libuuid', 'libunistring', 'gmp-native', 'libmpc-native', 'mpfr-native', 'xkeyboard-config', 'at-spi2-core', 'bzip2', 'elfutils-native', 'libpcre-native', 'zstd-native', 'gdbm', 'libtirpc', 'xz', 'libnsl2', 'sqlite3', 'vala', 'libmicrohttpd-native', 'libarchive-native', 'libgcrypt-native', 'gnutls-native', 'lzo-native', 'libgpg-error-native', 'libcap-native', 'libunistring-native', 'libidn2-native', 'nettle-native']
DEBUG: Python function extend_recipe_sysroot finished
DEBUG: Executing shell function do_configure
 0:00.40 Clobber not needed.
 0:00.40 Adding make options from /OE/build/test-oe-build-time/poky/build/tmp/work/core2-64-poky-linux/firefox/68.9.0esr-r0/firefox-68.9.0/mozconfig
    MOZ_OBJDIR=/OE/build/test-oe-build-time/poky/build/tmp/work/core2-64-poky-linux/firefox/68.9.0esr-r0/firefox-68.9.0/firefox-build-dir
    OBJDIR=/OE/build/test-oe-build-time/poky/build/tmp/work/core2-64-poky-linux/firefox/68.9.0esr-r0/firefox-68.9.0/firefox-build-dir
    FOUND_MOZCONFIG=/OE/build/test-oe-build-time/poky/build/tmp/work/core2-64-poky-linux/firefox/68.9.0esr-r0/firefox-68.9.0/mozconfig
    export FOUND_MOZCONFIG
 0:00.41 /OE/build/test-oe-build-time/poky/build/tmp/hosttools/make -f client.mk -s configure
 0:00.42 cd /OE/build/test-oe-build-time/poky/build/tmp/work/core2-64-poky-linux/firefox/68.9.0esr-r0/firefox-68.9.0/firefox-build-dir
 0:00.42 /OE/build/test-oe-build-time/poky/build/tmp/work/core2-64-poky-linux/firefox/68.9.0esr-r0/firefox-68.9.0/configure
 0:00.50 Creating Python environment
 0:00.81 /OE/build/test-oe-build-time/poky/build/tmp/work/core2-64-poky-linux/firefox/68.9.0esr-r0/firefox-68.9.0/third_party/python/virtualenv/virtualenv.py:25: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
 0:00.81   import distutils.spawn
 0:00.81 /OE/build/test-oe-build-time/poky/build/tmp/work/core2-64-poky-linux/firefox/68.9.0esr-r0/firefox-68.9.0/third_party/python/virtualenv/virtualenv.py:26: DeprecationWarning: The distutils.sysconfig module is deprecated, use sysconfig instead
 0:00.81   import distutils.sysconfig
 0:00.81 /OE/build/test-oe-build-time/poky/build/tmp/work/core2-64-poky-linux/firefox/68.9.0esr-r0/firefox-68.9.0/third_party/python/virtualenv/virtualenv.py:1047: DeprecationWarning: the imp module is deprecated in favour of importlib and slated for removal in Python 3.12; see the module's documentation for alternative uses
 0:00.81   import imp
 0:00.81 Using base prefix '/OE/build/test-oe-build-time/poky/build/tmp/work/core2-64-poky-linux/firefox/68.9.0esr-r0/recipe-sysroot-native/usr'
 0:00.81 New python executable in /OE/build/test-oe-build-time/poky/build/tmp/work/core2-64-poky-linux/firefox/68.9.0esr-r0/firefox-68.9.0/firefox-build-dir/_virtualenvs/init/bin/python3
 0:00.81 Also creating executable in /OE/build/test-oe-build-time/poky/build/tmp/work/core2-64-poky-linux/firefox/68.9.0esr-r0/firefox-68.9.0/firefox-build-dir/_virtualenvs/init/bin/python
 0:00.81 Traceback (most recent call last):
 0:00.81   File "/OE/build/test-oe-build-time/poky/build/tmp/work/core2-64-poky-linux/firefox/68.9.0esr-r0/firefox-68.9.0/third_party/python/virtualenv/virtualenv.py", line 2349, in <module>
 0:00.81     main()
 0:00.81   File "/OE/build/test-oe-build-time/poky/build/tmp/work/core2-64-poky-linux/firefox/68.9.0esr-r0/firefox-68.9.0/third_party/python/virtualenv/virtualenv.py", line 703, in main
 0:00.81     create_environment(home_dir,
 0:00.81   File "/OE/build/test-oe-build-time/poky/build/tmp/work/core2-64-poky-linux/firefox/68.9.0esr-r0/firefox-68.9.0/third_party/python/virtualenv/virtualenv.py", line 925, in create_environment
 0:00.81     py_executable = os.path.abspath(install_python(
 0:00.81   File "/OE/build/test-oe-build-time/poky/build/tmp/work/core2-64-poky-linux/firefox/68.9.0esr-r0/firefox-68.9.0/third_party/python/virtualenv/virtualenv.py", line 1444, in install_python
 0:00.81     fix_local_scheme(home_dir, symlink)
 0:00.81   File "/OE/build/test-oe-build-time/poky/build/tmp/work/core2-64-poky-linux/firefox/68.9.0esr-r0/firefox-68.9.0/third_party/python/virtualenv/virtualenv.py", line 1527, in fix_local_scheme
 0:00.81     if sysconfig._get_default_scheme() == 'posix_local':
 0:00.81 AttributeError: module 'sysconfig' has no attribute '_get_default_scheme'. Did you mean: 'get_default_scheme'?
 0:00.81 Traceback (most recent call last):
 0:00.81   File "/OE/build/test-oe-build-time/poky/build/tmp/work/core2-64-poky-linux/firefox/68.9.0esr-r0/firefox-68.9.0/configure.py", line 132, in <module>
 0:00.81     sys.exit(main(sys.argv))
 0:00.81   File "/OE/build/test-oe-build-time/poky/build/tmp/work/core2-64-poky-linux/firefox/68.9.0esr-r0/firefox-68.9.0/configure.py", line 38, in main
 0:00.81     sandbox.run(os.path.join(os.path.dirname(__file__), 'moz.configure'))
 0:00.81   File "/OE/build/test-oe-build-time/poky/build/tmp/work/core2-64-poky-linux/firefox/68.9.0esr-r0/firefox-68.9.0/python/mozbuild/mozbuild/configure/__init__.py", line 431, in run
 0:00.81     self.include_file(path)
 0:00.81   File "/OE/build/test-oe-build-time/poky/build/tmp/work/core2-64-poky-linux/firefox/68.9.0esr-r0/firefox-68.9.0/python/mozbuild/mozbuild/configure/__init__.py", line 422, in include_file
 0:00.81     exec_(code, self)
 0:00.81   File "/OE/build/test-oe-build-time/poky/build/tmp/work/core2-64-poky-linux/firefox/68.9.0esr-r0/firefox-68.9.0/python/mozbuild/mozbuild/util.py", line 59, in exec_
 0:00.81     exec(object, globals, locals)
 0:00.81   File "/OE/build/test-oe-build-time/poky/build/tmp/work/core2-64-poky-linux/firefox/68.9.0esr-r0/firefox-68.9.0/moz.configure", line 7, in <module>
 0:00.81     include('build/moz.configure/init.configure')
 0:00.81   File "/OE/build/test-oe-build-time/poky/build/tmp/work/core2-64-poky-linux/firefox/68.9.0esr-r0/firefox-68.9.0/python/mozbuild/mozbuild/configure/__init__.py", line 745, in include_impl
 0:00.81     self.include_file(what)
 0:00.81   File "/OE/build/test-oe-build-time/poky/build/tmp/work/core2-64-poky-linux/firefox/68.9.0esr-r0/firefox-68.9.0/python/mozbuild/mozbuild/configure/__init__.py", line 422, in include_file
 0:00.81     exec_(code, self)
 0:00.81   File "/OE/build/test-oe-build-time/poky/build/tmp/work/core2-64-poky-linux/firefox/68.9.0esr-r0/firefox-68.9.0/python/mozbuild/mozbuild/util.py", line 59, in exec_
 0:00.81     exec(object, globals, locals)
 0:00.81   File "/OE/build/test-oe-build-time/poky/build/tmp/work/core2-64-poky-linux/firefox/68.9.0esr-r0/firefox-68.9.0/build/moz.configure/init.configure", line 212, in <module>
 0:00.81     @imports('distutils.sysconfig')
 0:00.81   File "/OE/build/test-oe-build-time/poky/build/tmp/work/core2-64-poky-linux/firefox/68.9.0esr-r0/firefox-68.9.0/python/mozbuild/mozbuild/configure/__init__.py", line 728, in decorator
 0:00.81     depends = DependsFunction(self, func, dependencies, when=when)
 0:00.81   File "/OE/build/test-oe-build-time/poky/build/tmp/work/core2-64-poky-linux/firefox/68.9.0esr-r0/firefox-68.9.0/python/mozbuild/mozbuild/configure/__init__.py", line 125, in __init__
 0:00.81     sandbox._value_for(self)
 0:00.81   File "/OE/build/test-oe-build-time/poky/build/tmp/work/core2-64-poky-linux/firefox/68.9.0esr-r0/firefox-68.9.0/python/mozbuild/mozbuild/configure/__init__.py", line 525, in _value_for
 0:00.81     return self._value_for_depends(obj)
 0:00.81   File "/OE/build/test-oe-build-time/poky/build/tmp/work/core2-64-poky-linux/firefox/68.9.0esr-r0/firefox-68.9.0/python/mozbuild/mozbuild/util.py", line 947, in method_call
 0:00.81     cache[args] = self.func(instance, *args)
 0:00.81   File "/OE/build/test-oe-build-time/poky/build/tmp/work/core2-64-poky-linux/firefox/68.9.0esr-r0/firefox-68.9.0/python/mozbuild/mozbuild/configure/__init__.py", line 534, in _value_for_depends
 0:00.81     value = obj.result()
 0:00.81   File "/OE/build/test-oe-build-time/poky/build/tmp/work/core2-64-poky-linux/firefox/68.9.0esr-r0/firefox-68.9.0/python/mozbuild/mozbuild/util.py", line 947, in method_call
 0:00.81     cache[args] = self.func(instance, *args)
 0:00.81   File "/OE/build/test-oe-build-time/poky/build/tmp/work/core2-64-poky-linux/firefox/68.9.0esr-r0/firefox-68.9.0/python/mozbuild/mozbuild/configure/__init__.py", line 151, in result
 0:00.81     return self._func(*resolved_args)
 0:00.81   File "/OE/build/test-oe-build-time/poky/build/tmp/work/core2-64-poky-linux/firefox/68.9.0esr-r0/firefox-68.9.0/python/mozbuild/mozbuild/configure/__init__.py", line 1097, in wrapped
 0:00.81     return new_func(*args, **kwargs)
 0:00.81   File "/OE/build/test-oe-build-time/poky/build/tmp/work/core2-64-poky-linux/firefox/68.9.0esr-r0/firefox-68.9.0/build/moz.configure/init.configure", line 261, in virtualenv_python
 0:00.81     manager.build(python)
 0:00.81   File "/OE/build/test-oe-build-time/poky/build/tmp/work/core2-64-poky-linux/firefox/68.9.0esr-r0/firefox-68.9.0/python/mozbuild/mozbuild/virtualenv.py", line 473, in build
 0:00.81     self.create(python)
 0:00.81   File "/OE/build/test-oe-build-time/poky/build/tmp/work/core2-64-poky-linux/firefox/68.9.0esr-r0/firefox-68.9.0/python/mozbuild/mozbuild/virtualenv.py", line 212, in create
 0:00.81     'Failed to create virtualenv: %s' % self.virtualenv_root)
 0:00.81 Exception: Failed to create virtualenv: /OE/build/test-oe-build-time/poky/build/tmp/work/core2-64-poky-linux/firefox/68.9.0esr-r0/firefox-68.9.0/firefox-build-dir/_virtualenvs/init
 0:00.82 *** Fix above errors and then restart with\
 0:00.82                "./mach build"
 0:00.82 make: *** [client.mk:115: configure] Error 1
WARNING: /OE/build/test-oe-build-time/poky/build/tmp/work/core2-64-poky-linux/firefox/68.9.0esr-r0/temp/run.do_configure.334283:205 exit 2 from './mach "$@"'
WARNING: Backtrace (BB generated script):
	#1: mozilla_run_mach, /OE/build/test-oe-build-time/poky/build/tmp/work/core2-64-poky-linux/firefox/68.9.0esr-r0/temp/run.do_configure.334283, line 205
	#2: mozilla_do_configure, /OE/build/test-oe-build-time/poky/build/tmp/work/core2-64-poky-linux/firefox/68.9.0esr-r0/temp/run.do_configure.334283, line 189
	#3: do_configure, /OE/build/test-oe-build-time/poky/build/tmp/work/core2-64-poky-linux/firefox/68.9.0esr-r0/temp/run.do_configure.334283, line 168
	#4: main, /OE/build/test-oe-build-time/poky/build/tmp/work/core2-64-poky-linux/firefox/68.9.0esr-r0/temp/run.do_configure.334283, line 209

* as firefox-68 is way too old nowadays, it doesn't make much sense to
  spend more time trying to resolve this properly, add quick hack just
  to measure build time

(master rev: cb79ef0 )

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>
Signed-off-by: Randy MacLeod <Randy.MacLeod@windriver.com>